[toolchain]
anchor_version = "0.32.1"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
election = "EmzBbFz57z4S47eca95vPxSLFeotx4tTXmNK8cDd1sBJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx tests/election.ts"

[test]
startup_wait = 600000
shutdown_wait = 2000
upgradeable = false
